# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Build Stage first step
stage: Initial tests

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds.

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - SUNPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test --coverage'
        - EVENT_TYPE='pull_request push cron'
        - CONDA_DEPENDENCIES='openjpeg Cython jinja2 scipy matplotlib mock requests beautifulsoup4 sqlalchemy scikit-image pytest-mock pandas nomkl pytest-cov coverage glymur suds-jurko sphinx'
        - PIP_DEPENDENCIES='sunpy-sphinx-theme pytest-astropy'
        - CONDA_CHANNELS='sunpy'
    matrix:
        # Make sure that egg_info works without dependencies
        - PYTHON_VERSION=3.5 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.6 SETUP_CMD='egg_info'

stages:
   # Do the install jobs and one offline test, it will not proceed if any fail
   - name: Initial tests
   # Cron only tests
   - name: Cron tests
     if: type = cron
   # Do the rest of the tests
   - name: Comprehensive tests

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # Do a basic test.
        - os: linux
          stage: Initial tests
          env: SETUP_CMD='test --coverage'

        # Do a PEP8 test with pycodestyle
        - os: linux
          stage: Initial tests
          env: MAIN_CMD='pycodestyle ndcube --count' SETUP_CMD=''

        # Do a coverage test.
        - os: linux
          stage: Comprehensive tests
          env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - os: linux
          stage: Comprehensive tests
          env: SETUP_CMD='build_docs -w'

        # Astropy LTS
        - os: linux
          stage: Comprehensive tests
          env: ASTROPY_VERSION=lts

        # Astropy Master (CRON)
        - os: linux
          stage: Cron tests
          env: ASTROPY_VERSION=development

        # SunPy Master (CRON)
        - os: linux
          stage: Cron tests
          env: SUNPY_VERSION=development

        # Mac OS (CRON)
        - os: osx
          stage: Cron tests
          env: SETUP_CMD='test --coverage'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   - $MAIN_CMD $SETUP_CMD

after_success:
   - if [[ $SETUP_CMD = *"cov"* ]]; then pip install codecov; codecov; fi
