%YAML 1.1
---
id: asdf://sunpy.org/ndcube/manifests/ndcube-0.1.0
extension_uri: asdf://sunpy.org/extensions/ndcube-0.1.0
title: NDCube ASDF Manifest
description: ASDF schemas and tags for NDCube classes.

tags:
  - tag_uri: "tag:sunpy.org:ndcube/ndcube/ndcube-0.1.0"
    schema_uri: "asdf://sunpy.org/ndcube/schemas/ndcube-0.1.0"

  - tag_uri:  "tag:sunpy.org:ndcube/extra_coords/extra_coords/extracoords-0.1.0"
    schema_uri: "asdf://sunpy.org/ndcube/schemas/extra_coords-0.1.0"

  - tag_uri:  "tag:sunpy.org:ndcube/extra_coords/table_coord/timetablecoordinate-0.1.0"
    schema_uri: "asdf://sunpy.org/ndcube/schemas/timetablecoordinate-0.1.0"

  - tag_uri:  "tag:sunpy.org:ndcube/extra_coords/table_coord/quantitytablecoordinate-0.1.0"
    schema_uri: "asdf://sunpy.org/ndcube/schemas/quantitytablecoordinate-0.1.0"

  - tag_uri:  "tag:sunpy.org:ndcube/extra_coords/table_coord/skycoordtablecoordinate-0.1.0"
    schema_uri: "asdf://sunpy.org/ndcube/schemas/skycoordtablecoordinate-0.1.0"

  - tag_uri:  "tag:sunpy.org:ndcube/global_coords/globalcoords-0.1.0"
    schema_uri: "asdf://sunpy.org/ndcube/schemas/global_coords-0.1.0"

  - tag_uri:  "tag:sunpy.org:ndcube/resampledwcs-0.1.0"
    schema_uri: "asdf://sunpy.org/ndcube/schemas/resampledwcs-0.1.0"

  - tag_uri:  "tag:sunpy.org:ndcube/reorderedwcs-0.1.0"
    schema_uri: "asdf://sunpy.org/ndcube/schemas/reorderedwcs-0.1.0"

  - tag_uri:  "tag:sunpy.org:ndcube/compoundwcs-0.1.0"
    schema_uri: "asdf://sunpy.org/ndcube/schemas/compoundwcs-0.1.0"
